// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using notaria.DataContext;

#nullable disable

namespace notaria.Migrations
{
    [DbContext(typeof(NotariaContext))]
    partial class NotariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("notaria.DataEntities.ActoEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("diasHabiles")
                        .HasColumnType("int");

                    b.Property<int?>("numeroDePasos")
                        .HasColumnType("int");

                    b.Property<int?>("tipoActoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tipoActoId");

                    b.ToTable("Acto");
                });

            modelBuilder.Entity("notaria.DataEntities.ArchivoPasoTramiteEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("pasoTramiteId")
                        .HasColumnType("int");

                    b.Property<string>("urlArchivo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("usuarioCreoId")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioModificoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("pasoTramiteId");

                    b.HasIndex("usuarioCreoId");

                    b.ToTable("ArchivoPasoTramite");
                });

            modelBuilder.Entity("notaria.DataEntities.ArchivoTramiteEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime?>("fechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("tramiteId")
                        .HasColumnType("int");

                    b.Property<string>("urlArchivo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("usuarioCreoId")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioModificoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("tramiteId");

                    b.HasIndex("usuarioCreoId");

                    b.ToTable("ArchivoTramite");
                });

            modelBuilder.Entity("notaria.DataEntities.EstatusEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("estatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("Estatus");
                });

            modelBuilder.Entity("notaria.DataEntities.PasoActoEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("actoId")
                        .HasColumnType("int");

                    b.Property<bool?>("calificacionPositivoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<bool?>("campoRegistroPublicoPropiedad")
                        .HasColumnType("bit");

                    b.Property<bool?>("campoTrasladoDominio")
                        .HasColumnType("bit");

                    b.Property<bool?>("deRechazoActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("deSalidaActivoTD")
                        .HasColumnType("bit");

                    b.Property<int?>("diasHabiles")
                        .HasColumnType("int");

                    b.Property<bool?>("esParalelo")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaDeSalidaActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaEnviadoActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaPositivoFirmaActivoRPP")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaPositivoPagoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaPositivoSelloActivoRPP")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaRechazoActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaRechazoEnviadoActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaRechazoRevisionActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaReingresoRechazoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaRevisionActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("motivoRechazoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<bool?>("motivoRechazoActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("permitirArchivo")
                        .HasColumnType("bit");

                    b.Property<bool?>("positivoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<bool?>("rechazoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<string>("titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.HasIndex("actoId");

                    b.ToTable("PasoActo");
                });

            modelBuilder.Entity("notaria.DataEntities.RolEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("rolName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("notaria.DataEntities.TipoActoEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("numeroDePasos")
                        .HasColumnType("int");

                    b.Property<string>("tipoActo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("TipoActo");
                });

            modelBuilder.Entity("notaria.DataEntities.TokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Confirmado")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("notaria.DataEntities.TramiteEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int?>("actoId")
                        .HasColumnType("int");

                    b.Property<int?>("diasHabiles")
                        .HasColumnType("int");

                    b.Property<int?>("estatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaEscritura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaFirma")
                        .HasColumnType("datetime2");

                    b.Property<string>("numeroDeEscritura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parteA")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("parteB")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("actoId");

                    b.HasIndex("estatusId");

                    b.HasIndex("usuarioId");

                    b.ToTable("Tramite");
                });

            modelBuilder.Entity("notaria.DataEntities.TramitePasoEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool?>("calificacionPositivoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<string>("calificacionPositivoRPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("campoRegistroPublicoPropiedad")
                        .HasColumnType("bit");

                    b.Property<bool?>("campoTrasladoDominio")
                        .HasColumnType("bit");

                    b.Property<bool?>("deRechazoActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("deSalidaActivoTD")
                        .HasColumnType("bit");

                    b.Property<int?>("diasHabiles")
                        .HasColumnType("int");

                    b.Property<int?>("diasRetraso")
                        .HasColumnType("int");

                    b.Property<bool?>("esParalelo")
                        .HasColumnType("bit");

                    b.Property<int?>("estatusId")
                        .HasColumnType("int");

                    b.Property<bool?>("fechaDeSalidaActivoTD")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaDeSalidaTD")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("fechaEnviadoActivoTD")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaEnviadoTD")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("fechaPositivoFirmaActivoRPP")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaPositivoFirmaRPP")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("fechaPositivoPagoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaPositivoPagoRPP")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("fechaPositivoSelloActivoRPP")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaPositivoSelloRPP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaRealizado")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("fechaRechazoActivoTD")
                        .HasColumnType("bit");

                    b.Property<bool?>("fechaRechazoEnviadoActivoTD")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaRechazoEnviadoTD")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("fechaRechazoRevisionActivoTD")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaRechazoRevisionTD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaRechazoTD")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("fechaReingresoRechazoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaReingresoRechazoRPP")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("fechaRevisionActivoTD")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("fechaRevisionTD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("motivoReachazoTD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("motivoRechazoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<bool?>("motivoRechazoActivoTD")
                        .HasColumnType("bit");

                    b.Property<string>("motivoRechazoRPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("permitirArchivo")
                        .HasColumnType("bit");

                    b.Property<bool?>("positivoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<bool?>("rechazoActivoRPP")
                        .HasColumnType("bit");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("tramiteId")
                        .HasColumnType("int");

                    b.Property<int?>("usuarioId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("estatusId");

                    b.HasIndex("tramiteId");

                    b.HasIndex("usuarioId");

                    b.ToTable("TramitePaso");
                });

            modelBuilder.Entity("notaria.DataEntities.UserEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("modificar")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("rolId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("rolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("notaria.DataEntities.ActoEntity", b =>
                {
                    b.HasOne("notaria.DataEntities.TipoActoEntity", "TipoActoEntity")
                        .WithMany()
                        .HasForeignKey("tipoActoId");

                    b.Navigation("TipoActoEntity");
                });

            modelBuilder.Entity("notaria.DataEntities.ArchivoPasoTramiteEntity", b =>
                {
                    b.HasOne("notaria.DataEntities.TramitePasoEntity", "TramitePasoEntity")
                        .WithMany()
                        .HasForeignKey("pasoTramiteId");

                    b.HasOne("notaria.DataEntities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("usuarioCreoId");

                    b.Navigation("TramitePasoEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("notaria.DataEntities.ArchivoTramiteEntity", b =>
                {
                    b.HasOne("notaria.DataEntities.TramiteEntity", "TramiteEntity")
                        .WithMany()
                        .HasForeignKey("tramiteId");

                    b.HasOne("notaria.DataEntities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("usuarioCreoId");

                    b.Navigation("TramiteEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("notaria.DataEntities.PasoActoEntity", b =>
                {
                    b.HasOne("notaria.DataEntities.ActoEntity", "ActoEntity")
                        .WithMany("PasoActoEntity")
                        .HasForeignKey("actoId");

                    b.Navigation("ActoEntity");
                });

            modelBuilder.Entity("notaria.DataEntities.TramiteEntity", b =>
                {
                    b.HasOne("notaria.DataEntities.ActoEntity", "ActoEntity")
                        .WithMany()
                        .HasForeignKey("actoId");

                    b.HasOne("notaria.DataEntities.EstatusEntity", "EstatusEntity")
                        .WithMany()
                        .HasForeignKey("estatusId");

                    b.HasOne("notaria.DataEntities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("usuarioId");

                    b.Navigation("ActoEntity");

                    b.Navigation("EstatusEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("notaria.DataEntities.TramitePasoEntity", b =>
                {
                    b.HasOne("notaria.DataEntities.EstatusEntity", "EstatusEntity")
                        .WithMany()
                        .HasForeignKey("estatusId");

                    b.HasOne("notaria.DataEntities.TramiteEntity", "TramiteEntity")
                        .WithMany("PasosTramite")
                        .HasForeignKey("tramiteId");

                    b.HasOne("notaria.DataEntities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("usuarioId");

                    b.Navigation("EstatusEntity");

                    b.Navigation("TramiteEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("notaria.DataEntities.UserEntity", b =>
                {
                    b.HasOne("notaria.DataEntities.RolEntity", "RolEntity")
                        .WithMany()
                        .HasForeignKey("rolId");

                    b.Navigation("RolEntity");
                });

            modelBuilder.Entity("notaria.DataEntities.ActoEntity", b =>
                {
                    b.Navigation("PasoActoEntity");
                });

            modelBuilder.Entity("notaria.DataEntities.TramiteEntity", b =>
                {
                    b.Navigation("PasosTramite");
                });
#pragma warning restore 612, 618
        }
    }
}
